export interface Cafe {
    id:number,
    name: string,
    shortDescription: string,
    description: string,
    city: string,
    address: string,
    hours: string,
    priceLevel: string,
    minOrder: number,
    noiseLevel: string,
    tablesNumber: number,
    latitude: null,
    longitude: null,
    veganOption: boolean,
    alcohol: boolean,
    eventRoom: boolean,
    rating: null,
    instagramLink: string | null,
    facebookLink: string | null,
    websiteLink: string | null,
    imageLink: string[],
    optionNames: string[],
    logoLink: string,
    commentIds: number[]
}

